# Generated by Django 4.0.10 on 2024-11-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
