# Generated by Django 4.0.10 on 2024-11-01 21:46

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_email_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fecha_vencimiento',
            field=models.DateField(default=task.models.default_fecha_vencimiento),
        ),
    ]
