# Generated by Django 4.0.10 on 2024-11-01 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'user'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
